<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-07T00:40:19 IST" name="Suite" finished-at="2022-07-07T00:42:50 IST" duration-ms="151037">
    <groups>
    </groups>
    <test started-at="2022-07-07T00:40:19 IST" name="Test" finished-at="2022-07-07T00:42:50 IST" duration-ms="151037">
      <class name="com.ob.tests.DepositAmount">
        <test-method is-config="true" signature="launchingApp(java.lang.String,java.lang.reflect.Method,org.testng.ITestContext)[pri:0, instance:com.ob.tests.DepositAmount@7d4f9aae]" started-at="2022-07-07T00:41:41 IST" name="launchingApp" finished-at="2022-07-07T00:41:50 IST" duration-ms="8461" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.ob.tests.DepositAmount.depositAmount() throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@6002e944]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingApp -->
        <test-method signature="depositAmount()[pri:0, instance:com.ob.tests.DepositAmount@7d4f9aae]" started-at="2022-07-07T00:41:50 IST" name="depositAmount" finished-at="2022-07-07T00:42:50 IST" duration-ms="60490" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- depositAmount -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.ob.tests.DepositAmount@7d4f9aae]" started-at="2022-07-07T00:42:50 IST" name="closeBrowser" finished-at="2022-07-07T00:42:50 IST" duration-ms="396" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.ob.tests.DepositAmount -->
      <class name="com.ob.tests.creatingUser">
        <test-method is-config="true" signature="initializeReport()[pri:0, instance:com.ob.tests.creatingUser@d9345cd]" started-at="2022-07-07T00:40:19 IST" name="initializeReport" finished-at="2022-07-07T00:40:19 IST" duration-ms="379" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeReport -->
        <test-method is-config="true" signature="launchingApp(java.lang.String,java.lang.reflect.Method,org.testng.ITestContext)[pri:0, instance:com.ob.tests.creatingUser@d9345cd]" started-at="2022-07-07T00:40:19 IST" name="launchingApp" finished-at="2022-07-07T00:40:38 IST" duration-ms="18978" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.ob.tests.creatingUser.createUser() throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@6002e944]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingApp -->
        <test-method signature="createUser()[pri:0, instance:com.ob.tests.creatingUser@d9345cd]" started-at="2022-07-07T00:40:38 IST" name="createUser" finished-at="2022-07-07T00:40:41 IST" duration-ms="2710" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertFalse(Assert.java:78)
at org.testng.Assert.assertFalse(Assert.java:88)
at com.ob.tests.creatingUser.createUser(creatingUser.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.ob.tests.creatingUser@d9345cd]" started-at="2022-07-07T00:41:41 IST" name="closeBrowser" finished-at="2022-07-07T00:41:41 IST" duration-ms="214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="closeReport()[pri:0, instance:com.ob.tests.creatingUser@d9345cd]" started-at="2022-07-07T00:42:50 IST" name="closeReport" finished-at="2022-07-07T00:42:51 IST" duration-ms="508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeReport -->
      </class> <!-- com.ob.tests.creatingUser -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
